export const HOME_CLICKED = "HOME_CLICKED";
export const ABOUT_CLICKED = "ABOUT_CLICKED";
export const SKILLS_CLICKED = "SKILLS_CLICKED";
export const SERVICE_CLICKED = "SERVICE_CLICKED";
export const PORTFOLOIO_CLICKED = "PORTFOLOIO_CLICKED";
export const CONTACT_CLICKED = "CONTACT_CLICKED";
